#!/usr/bin/bash

# AZP Paket Sistemi 1.5
# 2021 AZP
# 2019-2021 PacPERRO OS

# Root kontrol
if [[ ! $UID -eq 0 ]] ; then
    echo -e "\033[1;31m Xahiş edirik root ilə açın ! \033[:0m"
    echo -e "\033[1;31m Please open with root! \033[:0m"
    exit 1
fi

# Lazımlı paketlərin yoxlanılması
paket="zip unzip"
if ! which $paket &> /dev/null;
then
  echo -e "\033[1;32m Lazımlı paketlər yüklənir... \033[:0m"
  apt-get install $paket -y &> /dev/null
else
  echo ""
fi



echo """

                AZP 1.5

 PacPERRO OS üçün hazırlanmış paket sistemi
 (Package system developed for PacPERRO OS)

  azp -i package.azp = Paket quraşdırma (install package)
  azp -r application = Paketi silmək (remove package)
  azp -a application = Program haqqında məlumat (Information about the program)
  azp -pl = Quraşdırılmış programların listəsini yaradır (Creates a list of installed programs)
  azp -di package = Depodan programlar quraşdırma (Installing programs from the repository)
  azp -dpl = Depodakı kategoriyalarda hansı programların olduğunu göstərir.

   AZP Rəsmi Saytı (Offical Site): https://azp-paket-sistemi.github.io
   AZP Depo: https://azp-paket-sistemi.github.io/azp-depo
   Web Saytımız: https://pacperro-os.github.io

          2019-2021 PacPERRO OS
          2021 AZP
"""
mkdir -p /var/cache/azp &>/dev/null

# Paket quraşdırma
if [ $1 == "-i" ] &>/dev/null
then
  paket_adi=$2
  mkdir /tmp/azptmp
  if ! unzip $paket_adi -d /tmp/azptmp &> /dev/null;
  then
    echo -e "\033[1;31m Paket Tapılmadı ! \033[:0m"
    exit
  else
    echo -e "\033[1;34m Fayllar Çıxarılır... \033[:0m"
  fi
  cd /tmp/azptmp
  if [ -f fayllar ]
  then
    echo ""
  else
    echo "'fayllar' tapılmadı, paket keçərsizdir"
    rm -r /tmp/azptmp
    exit
  fi
  if [ -f info ]
  then
    echo ""
  else
    echo "'info' tapılmadı, paket keçərsizdir"
    rm -r /tmp/azptmp
    exit
  fi
  if [ -f program-adı ]
  then
    echo ""
  else
    echo "'program-adı' tapılmadı, paket keçərsizdir"
    rm -r /tmp/azptmp
    exit
  fi
  if [ -f src.tar.bz2 ]
  then
    echo ""
  else
    echo "'src.tar.bz2' tapılmadı, paket keçərsizdir"
    rm -r /tmp/azptmp &>/dev/null
    exit
  fi
  i_program=`cat program-adı`
  if [ -d /var/cache/azp/$i_program ]
  then
    echo -e "\033[1;31m Bu program əvvəldən quraşdırılmışdır, yenisi ilə əvəz olunacaqdır... \033[:0m"
    /var/cache/azp/`cat program-adı`/azprm &>/dev/null
  else
    echo ""
  fi
  i_program=`cat program-adı`
  mkdir -p /var/cache/azp/$i_program
  cp -r info /var/cache/azp/$i_program
  cp -r program-adı /var/cache/azp/$i_program
  cp -r fayllar /var/cache/azp/$i_program
  echo '#!/usr/bin/bash' >> /var/cache/azp/$i_program/azprm
  echo 'fayllar=`cat fayllar`' >> /var/cache/azp/$i_program/azprm
  echo 'rm -r $fayllar' >> /var/cache/azp/$i_program/azprm
  echo 'i_program=`cat program-adı`' >> /var/cache/azp/$i_program/azprm
  echo 'rm -r /var/cache/azp/$i_program' >> /var/cache/azp/$i_program/azprm
  chmod u+x /var/cache/azp/$i_program/azprm
  mkdir azpsrc
  if ! tar -xf src.tar.bz2 -C azpsrc &>/dev/null;
  then
    echo -e "\033[1;31m 'src' faylında problem baş verdi ! \033[:0m"
    exit
    rm -r /tmp/azptmp
  else
    echo -e "\033[1;34m Fayllar fayl sisteminə kopyalanır... \033[:0m"
  fi
  sleep 1
  cd azpsrc
  cp -prf * /
  cd ..
  cd ..
  rm -r azptmp
  echo -e "\033[1;32m Quraşdırma bitmişdir \033[0m"
fi

# Program Silmə
if [ $1 == "-r" ] &>/dev/null
then
  r_program=$2
  read -p "Programı silmək istədiyinizdən əminsiniz ? [h/y]: " program_r_secim
  if [ $program_r_secim == "h" ]
  then
    cd /var/cache/azp/ &>/dev/null
    cd $r_program &>/dev/null
    if ! /var/cache/azp/$r_program/azprm &>/dev/null;
    then
      echo -e "\033[1;31m Belə bir program yoxdur ! \033[:0m"
      exit
    else
      echo ""
    fi
    sleep 1
    echo -e "\e[1;32m Proses Bitdi \033[:0m"
    cd ..
  fi
  if [ $program_r_secim == "y" ]
  then
     exit
  fi
fi

# Program Haqqında Məlumat
if [ $1 == "-a" ] &>/dev/null
then
   program_info=$2
   echo "-------------------"
   if ! echo -e "\033[1;37m`cat /var/cache/azp/$program_info/info`\033[:0m";
   then
     echo -e "\033[1;31m Belə bir program yoxdur ! \033[:0m"
     exit
   else
     echo ""
   fi
fi

# Quraşdırılan programlar listəsi
if [ $1 == "-pl" ] &>/dev/null
then
  cd /var/cache/azp &>/dev/null
  echo -e "\033[1;33m `ls` \033[:0m"
  ls > /home/program-list
  echo "----------------------"
  echo -e "\033[1;32m 'program-list' yaradıldı. /home bölümündən götürün \033[:0m"
fi

# Depodan yükləmə və quraşdırma
if [ $1 == "-di" ] &>/dev/null
then
  wget -q --tries=10 --timeout=20 --spider https://azp-paket-sistemi.github.io/azp-depo
  if [[ $? -eq 0 ]]; 
  then
    echo ""
  else
    echo -e "\033[1;31m İnternet bağlantısını yoxlayın və yenidən cəhd edin \033[:0m"
    exit
  fi
  if ! which wget &> /dev/null;
  then
    echo -e "\033[1;32m Lazımlı paketlər yüklənir... \033[:0m"
    apt-get install wget -y &> /dev/null
  else
    echo ""
  fi
  mkdir -p /var/cache/azp-depoins
  cd /var/cache/azp-depoins &>/dev/null
  depo_app=$2
  repo_ad=$depo_app
  if ! wget https://azp-paket-sistemi.github.io/azp-depo/${repo_ad:0:1}/$repo_ad/latest-file &>/dev/null;
  then
    echo -e "\033[1;31m Repo faylı yüklənmədi ! \033[:0m"
    rm -r /var/cache/azp-depoins
    exit
  else
    echo ""
  fi
  echo -e "\033[1;34m Repo faylı oxunur... \033[:0m"
  latest_file=`cat latest-file` &>/dev/null
  echo -e "\033[1;34m Paket Yüklənir... \033[:0m"
  if ! wget https://azp-paket-sistemi.github.io/azp-depo/${repo_ad:0:1}/$repo_ad/$latest_file &>/dev/null;
  then
    echo -e "\033[1;31m Paket yüklənmədi ! \033[:0m"
    rm -r /var/cache/azp-depoins
    exit
  else
    echo ""
  fi
  echo -e "\033[1;34m Paket Quraşdırılır... \033[:0m"
  if ! azp -i $latest_file &>/dev/null;
  then
    echo -e "\033[1;31m AZP Çalışmadı ! /usr/bin içərisindən yoxdur \033[:0m"
    rm -r /var/cache/azp-depoins
    exit
  else
    echo ""
  fi
  echo -e "\033[1;32m Proses Bitdi \033[:0m"
  cd ..
  rm -r /var/cache/azp-depoins
fi

if [ $1 == "-dpl" ] &>/dev/null
then
  read -p "Kategoriya [a,b,c]: " depo_pl
  if ! wget https://azp-paket-sistemi.github.io/azp-depo/$depo_pl/program-list &>/dev/null;
  then
    echo -e "\033[1;31m Belə bir kategoriya yoxdur ! \033[:0m"
    exit
  else
    echo ""
  fi
  mv program-list /home/depo-list
  echo -e "\033[1;32m '$depo_pl' kategoriyasındakı programlar: \033[:0m"
  echo -e "\033[1;34m `cat /home/depo-list` \033[:0m"
fi